apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app20
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app20
  template:
    metadata:
      labels:
        app: flask-app20
    spec:
      containers:
      - name: flask-app20
        image: hruthingali/flask-app20:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: LoadBalancer
  selector:
    app: flask-app20
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
