apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app20
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app20
  template:
    metadata:
      labels:
        app: flask-app20
    spec:
      containers:
      - name: flask-app20
        image: hruthingali/flask-app20:latest
        ports:
        - containerPort: 5000
